server:
  port: 8081

spring:
  datasource:
    # MySQL 数据库连接配置
    url: jdbc:mysql://localhost:3306/ai?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 238729046
    driver-class-name: com.mysql.cj.jdbc.Driver

    # 连接池配置
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  jpa:
    hibernate:
      # 数据库表结构管理方式
      # create: 每次启动都重新创建表（会丢失数据）
      # create-drop: 创建表，关闭时删除表
      # update: 更新表结构（推荐用于开发环境）
      # validate: 验证表结构
      # none: 不做任何操作
      ddl-auto: update
    show-sql: true  # 显示SQL语句（开发环境建议开启）
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true  # 格式化SQL输出
        use_sql_comments: true  # 显示SQL注释

  servlet:
    multipart:
      max-file-size: 100MB  # 单个文件最大大小
      max-request-size: 100MB  # 请求最大大小
      enabled: true

# 日志配置
logging:
  level:
    com.onlinestudy: DEBUG  # 应用日志级别
    org.hibernate.SQL: DEBUG  # Hibernate SQL日志
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # SQL参数日志
